-- 코드를 입력하세요
# SELECT *
SELECT B.AUTHOR_ID, A.AUTHOR_NAME, B.CATEGORY, SUM(B.PRICE * SALES) TOTAL_SALES
FROM BOOK B
JOIN AUTHOR A
USING(AUTHOR_ID)
JOIN BOOK_SALES S
ON B.BOOK_ID = S.BOOK_ID AND SALES_DATE BETWEEN '2022-01-01' AND '2022-01-31'
GROUP BY 1, 3
ORDER BY 1, 3 DESC;

