-- 코드를 작성해주세요

WITH R AS (
    SELECT ID, PERCENT_RANK() OVER(ORDER BY SIZE_OF_COLONY DESC) SIZE_RANK
    FROM ECOLI_DATA
)

SELECT ID,
    CASE
        WHEN SIZE_RANK <= 0.25 THEN 'CRITICAL'
        WHEN SIZE_RANK <= 0.50 THEN 'HIGH'
        WHEN SIZE_RANK <= 0.75 THEN 'MEDIUM'
        ELSE 'LOW'
    END COLONY_NAME
FROM R
ORDER BY ID;