-- 코드를 입력하세요

WITH USERS AS (
    SELECT USER_ID
    FROM USER_INFO
    WHERE YEAR(JOINED) = 2021
)

# SELECT YEAR(SALES_DATE), MONTH(SALES_DATE), COUNT(*) AS PUCHASED_USERS, PUCHASED_RATIO
SELECT 
    YEAR(SALES_DATE) YEAR, 
    MONTH(SALES_DATE) MONTH,
    COUNT(DISTINCT(O.USER_ID)) PUCHASED_USERS,
    ROUND(COUNT(DISTINCT(O.USER_ID)) / (SELECT COUNT(*) FROM USERS), 1) PUCHASED_RATIO
FROM USERS U
JOIN ONLINE_SALE O
USING(USER_ID)
GROUP BY 1, 2
ORDER BY 1, 2;