-- 코드를 입력하세요

WITH CNTS AS (
    SELECT MEMBER_NAME, MEMBER_ID, COUNT(*) CNT
    FROM MEMBER_PROFILE M
    JOIN REST_REVIEW  R
    USING(MEMBER_ID)
    GROUP BY M.MEMBER_ID
    ORDER BY 3 DESC
    LIMIT 1
)

SELECT MEMBER_NAME, REVIEW_TEXT, DATE_FORMAT(REVIEW_DATE, '%Y-%m-%d') AS REVIEW_DATE
FROM REST_REVIEW
JOIN CNTS
USING(MEMBER_ID)
ORDER BY 3, 2;
