-- 코드를 작성해주세요
# I.ITEM_ID, I.ITEM_NAME, I.RARITY
SELECT II.ITEM_ID, II.ITEM_NAME, II.RARITY
FROM ITEM_INFO I
JOIN ITEM_TREE T
ON I.ITEM_ID = T.PARENT_ITEM_ID
JOIN ITEM_INFO II
ON T.ITEM_ID = II.ITEM_ID
WHERE I.RARITY = 'RARE'
ORDER BY II.ITEM_ID DESC;