-- 코드를 작성해주세요
WITH MS AS (
    SELECT YEAR(DIFFERENTIATION_DATE) AS YEAR, MAX(SIZE_OF_COLONY) AS MAX_SIZE
    FROM ECOLI_DATA
    GROUP BY YEAR
)

SELECT YEAR(D.DIFFERENTIATION_DATE) AS YEAR, (M.MAX_SIZE - D.SIZE_OF_COLONY) AS YEAR_DEV, ID
FROM ECOLI_DATA D
JOIN MS M
ON YEAR(D.DIFFERENTIATION_DATE) = M.YEAR
ORDER BY 1, 2;