-- 코드를 입력하세요
WITH MAX_CATEGORY AS (
    SELECT CATEGORY, MAX(PRICE) MAX_PRICE
    FROM FOOD_PRODUCT
    GROUP BY CATEGORY
    HAVING CATEGORY IN('과자', '국', '김치', '식용유')
)

SELECT M.CATEGORY, M.MAX_PRICE, P.PRODUCT_NAME FROM MAX_CATEGORY M
JOIN FOOD_PRODUCT P
ON P.PRICE = M.MAX_PRICE AND M.CATEGORY = P.CATEGORY
ORDER BY 2 DESC;
